# Generated by Django 5.1.3 on 2024-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('desc_task', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
