# Generated by Django 5.1.3 on 2024-11-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0002_task_board_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_board',
            old_name='desc_task',
            new_name='desc_project',
        ),
        migrations.RenameField(
            model_name='task_board',
            old_name='task_name',
            new_name='project_name',
        ),
        migrations.CreateModel(
            name='Task_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('responcile', models.CharField(max_length=30)),
                ('boarr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='msr.task_board')),
            ],
        ),
    ]
