# Generated by Django 5.1.3 on 2024-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0003_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='add_project',
        ),
    ]
