# Generated by Django 5.1.3 on 2024-12-08 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0004_rename_test_add_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_project',
            options={'verbose_name': 'Add Project', 'verbose_name_plural': 'Add Projects'},
        ),
        migrations.AlterModelOptions(
            name='task_board',
            options={'ordering': ['-created_on'], 'verbose_name': 'Task Board', 'verbose_name_plural': 'Task Boards'},
        ),
        migrations.AlterModelOptions(
            name='task_desc',
            options={'ordering': ['-created_on'], 'verbose_name': 'Task Description', 'verbose_name_plural': 'Task Descriptions'},
        ),
        migrations.RemoveField(
            model_name='task_desc',
            name='responcile',
        ),
        migrations.AddField(
            model_name='task_board',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_board',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_desc',
            name='responsible',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Responsible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_project',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='task_board',
            name='desc_project',
            field=models.CharField(max_length=150, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='task_board',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='task_desc',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='msr.task_board', verbose_name='Task Board'),
        ),
        migrations.AlterField(
            model_name='task_desc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='task_desc',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='task_desc',
            name='task_desc',
            field=models.CharField(max_length=150, verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task_desc',
            name='task_name',
            field=models.CharField(max_length=20, verbose_name='Task Name'),
        ),
    ]
